import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { FONT_DISPLAY, FONT_MONO, REQUIRED_FONTS } from "./fonts";
import coverage from "./fonts/coverage.json";

/**
 * The type stack's coverage guard.
 *
 * The failure this exists to catch is silent: drop a new symbol into a UI string
 * and it renders in whatever face the browser falls back to, at the wrong width,
 * breaking the character-cell alignment the HUD is built on. Nothing throws and
 * nothing looks broken in a diff — you only notice by staring at the running game.
 *
 * So: scan every shipped string for non-ASCII characters and assert the fonts
 * actually have them. `coverage.json` is generated by
 * `tools/font/build_symbols.py` from the two mono faces' cmaps, because vitest
 * runs in node with no font library and cannot read a brotli-compressed woff2.
 */

const ROOT = join(__dirname, "..", "..");
const covered = new Set(coverage.codepoints);

/** Files whose *strings* reach a player: the game's own source plus the shells. */
function shippedFiles(): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir)) {
      const path = join(dir, entry);
      if (statSync(path).isDirectory()) {
        // `tools/` is offline CLI tooling — its output goes to a terminal, not a canvas.
        if (entry !== "tools" && entry !== "fonts") walk(path);
      } else if (entry.endsWith(".ts") && !entry.endsWith(".test.ts")) {
        out.push(path);
      }
    }
  };
  walk(join(ROOT, "src"));
  for (const shell of ["index.html", "compliance-demo.html", "qualia-demo.html"]) {
    out.push(join(ROOT, shell));
  }
  return out;
}

/**
 * Strips comments so prose about a glyph isn't mistaken for a glyph being drawn.
 *
 * Crude but sufficient: this codebase writes `//`, `/* *\/` and jsdoc-style
 * leading-asterisk lines, and nothing puts a comment marker inside a string
 * literal. If that ever stops holding, the symptom is a spurious failure naming
 * the file — annoying, not misleading.
 */
function stripComments(source: string): string {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^[ \t]*\/\/.*$/gm, "")
    .replace(/^[ \t]*\*.*$/gm, "");
}

describe("font coverage", () => {
  it("covers every non-ASCII character in shipped strings", () => {
    const missing = new Map<string, Set<string>>();

    for (const path of shippedFiles()) {
      const body = stripComments(readFileSync(path, "utf8"));
      for (const ch of body) {
        const cp = ch.codePointAt(0)!;
        if (cp < 128 || covered.has(cp)) continue;
        const label = `${ch} (U+${cp.toString(16).toUpperCase().padStart(4, "0")})`;
        if (!missing.has(label)) missing.set(label, new Set());
        missing.get(label)!.add(path.slice(ROOT.length + 1));
      }
    }

    const report = [...missing].map(([ch, files]) => `${ch} in ${[...files].join(", ")}`);
    expect(report, `characters with no glyph in the font stack:\n  ${report.join("\n  ")}`).toEqual([]);
  });

  it("covers the fourteen symbols the symbol font was drawn for", () => {
    // Spelled out rather than derived, so deleting a glyph from the generator
    // fails here instead of quietly reducing coverage.
    const symbols = "←↑→↓⏸⓿▸◈○◎⚠✓✔✖";
    expect(symbols).toHaveLength(14);
    for (const ch of symbols) {
      expect(covered.has(ch.codePointAt(0)!), `${ch} missing from coverage.json`).toBe(true);
    }
  });

  it("keeps the base face ahead of the symbol face in every stack", () => {
    // Order is load-bearing: the symbol font has only 14 glyphs, so if it came
    // first every other character would miss it and fall through. Harmless today,
    // but it would make the stack's intent unreadable.
    for (const stack of [FONT_MONO, FONT_DISPLAY]) {
      expect(stack.indexOf("Share Tech Mono")).toBeLessThan(stack.indexOf("Article Zero Symbols"));
      expect(stack).toMatch(/monospace$/);
    }
    // The display stack leads with the proportional cut.
    expect(FONT_DISPLAY.indexOf('"Share Tech"')).toBe(0);
  });

  it("waits on every family the stacks name", () => {
    // A family in the stack but not in REQUIRED_FONTS is one the boot gate does
    // not await — the exact race that leaves Phaser text stuck in the fallback.
    for (const family of REQUIRED_FONTS) {
      expect(`${FONT_MONO} ${FONT_DISPLAY}`).toContain(`"${family}"`);
    }
    expect(REQUIRED_FONTS).toContain("Article Zero Symbols");
  });

  it("declares the same families in coverage.json that it loads", () => {
    expect(coverage.families).toEqual(["Share Tech Mono", "Article Zero Symbols"]);
  });
});
