import FRAMES from "./radarDirectionFrames.json";

/**
 * Which frame each of the radar bezel's eight compass ticks shows.
 *
 * Kept free of Phaser so the encoding can be tested without a scene, the same
 * split {@link ./NetworkPanel} uses: this module is arithmetic and a clock, and
 * `src/ui/Radar.ts` is the only thing that owns Game Objects.
 *
 * The frame map is generated by `tools/radar/build_radar_bezel.py` from the
 * artist's tags, so the loudness bands below are the only judgement written down
 * here — everything about *where* a frame lives is read, not restated.
 */

/** Sector order, matching the sheet's row order and `Radar.ts`'s sector indices. */
export const DIRECTIONS = [
  "east", "southeast", "south", "southwest",
  "west", "northwest", "north", "northeast",
] as const;

export type Direction = (typeof DIRECTIONS)[number];
export type TickState = keyof typeof FRAMES.states;

/** The tick sprite's authored size, and the size it is drawn at. */
export const TICK_SIZE = FRAMES.tickSize;
/** The whole grid, gaps included — what Phaser derives and tests bound-check. */
export const TICK_FRAME_COUNT = FRAMES.frameCount;

/**
 * Where each tick sits inside the 96x96 bezel, top-left relative.
 *
 * Generated alongside the sheet from the ink itself, so nudging a tick in
 * Aseprite and re-running the tool is the whole migration.
 */
export function tickOffset(dir: Direction): { x: number; y: number } {
  const spec = FRAMES.directions[dir];
  return { x: spec.x, y: spec.y };
}

/** The sheet frame showing `dir` in `state`. */
export function tickFrame(dir: Direction, state: TickState): number {
  return FRAMES.directions[dir].base + FRAMES.states[state];
}

/**
 * Loudness bands, as fractions of the way from a source's edge to its centre.
 *
 * `buildRadarSnapshot` hands over `1 - d/radius` — the same figure `emitAt`
 * gives a guard — so these are "how far inside the sound you are", not absolute
 * volume. Standing near the rim of a breaker's seven tiles reads quiet, and the
 * same tick goes red as you close on it, which is the useful thing to know.
 */
const LOUD_AT = 0.66;
const MEDIUM_AT = 0.33;

/** The lit state for a bearing at `level`, or `null` when nothing is audible. */
export function stateForLevel(level: number): TickState | null {
  if (level <= 0) return null;
  if (level >= LOUD_AT) return "loud";
  if (level >= MEDIUM_AT) return "medium";
  return "quiet";
}

// --- the blink, as a pure function of the clock -----------------------------
//
// Read straight off the artist's frame durations, `[36, 1260, 100, 36, …]`.
// Pure rather than driven by a `TimerEvent` for the reason `alertPulse` is:
// a timer that outlives its widget keeps firing into destroyed Game Objects.

/** Idle sweep: a 36ms flash once every 1296ms, so the ring reads as alive. */
const SCAN_LIT_MS = 36;
const SCAN_CYCLE_MS = 1296;

/** An audible source: 100ms lit, 36ms dark — urgent next to the idle sweep. */
const SOURCE_LIT_MS = 100;
const SOURCE_CYCLE_MS = 136;

/** Whether the idle `ping` is showing at `nowMs`. */
export function scanPulse(nowMs: number): boolean {
  return nowMs % SCAN_CYCLE_MS < SCAN_LIT_MS;
}

/** Whether an audible bearing is on its lit half at `nowMs`. */
export function sourcePulse(nowMs: number): boolean {
  return nowMs % SOURCE_CYCLE_MS < SOURCE_LIT_MS;
}

/**
 * The frame one bearing shows this instant.
 *
 * Silent bearings idle on the slow cyan sweep; audible ones blink their loudness
 * band. Both fall back to the same dark tick, so an unlit bearing is unlit for
 * one reason and looks it.
 */
export function frameFor(dir: Direction, level: number, nowMs: number): number {
  const state = stateForLevel(level);
  if (state === null) {
    return tickFrame(dir, scanPulse(nowMs) ? "ping" : "dark");
  }
  return tickFrame(dir, sourcePulse(nowMs) ? state : "dark");
}

/**
 * The frame one bearing shows while the signal is jammed.
 *
 * The artist's `JAMMED` tag spans frames 2-7 — loud, dark, medium, dark, quiet,
 * dark — which played as a loop is a readout cycling colours that mean nothing.
 * That is the jam: the scope already answers ALERT with red static rather than
 * going blank, and the ring answers it with garbage rather than going dark.
 *
 * Offset per bearing so the eight do not strobe in unison, which would read as
 * an intentional signal rather than as interference.
 */
const JAM_CYCLE: readonly TickState[] = ["loud", "dark", "medium", "dark", "quiet", "dark"];
const JAM_STEP_MS = 68;

export function jammedFrameFor(dir: Direction, nowMs: number): number {
  const spin = Math.floor(nowMs / JAM_STEP_MS) + DIRECTIONS.indexOf(dir) * 2;
  return tickFrame(dir, JAM_CYCLE[((spin % JAM_CYCLE.length) + JAM_CYCLE.length) % JAM_CYCLE.length]);
}
