import Phaser from "phaser";
import { DIRS_8, angleOf, type Dir8 } from "./directions";
import {
  DRONE_SILHOUETTE,
  ENFORCER_SILHOUETTE,
  ORDERLY_SILHOUETTE,
  PLAYER_SILHOUETTE,
  SECURITY_SILHOUETTE,
  type Silhouette,
} from "./Silhouette";
import {
  PLAYER_ANIM_FRAME_COUNTS,
  playerFrameKey,
  type PlayerAnimName,
} from "./PlayerAnimations";
import { ORDERLY_ANIM_FRAME_COUNTS, orderlyFrameKey, type OrderlyAnimName } from "./OrderlyAnimations";
import { ENFORCER_SKIN } from "./EnforcerAnimations";
import { DRONE_SKIN } from "./DroneAnimations";
import { SECURITY_SKIN } from "./SecurityGuardAnimations";
import type { GuardSkin } from "./GuardSkin";

/**
 * The cast, drawn rather than loaded.
 *
 * Rowan, the orderlies, the enforcers and the drones used to be 516 PNGs
 * generated by PixelLab — 2.5 MB of art, a generator under `tools/pixellab/`,
 * and a silhouette tracer whose output had to be regenerated whenever any of it
 * changed. All of that is gone. This module draws the same cast out of a handful
 * of shapes at boot instead, the way `Vent4Boss`, `BossCore`, `RoofRelay` and
 * `Sensor` have always drawn themselves.
 *
 * ### It generates textures, not sprites
 *
 * The obvious way to do procedural characters is to draw them every frame with a
 * `Graphics`. This doesn't: it renders each pose once into a texture under the
 * *same key the sprite sheets used*, so `Player`, `Enforcer`, `Drone` and
 * `Orderly` keep playing ordinary Phaser animations and none of their code
 * changes. That matters for more than tidiness — the player's stance machine is
 * driven by animation completion (`crouch-down` and `crouch-up` are one-shots
 * whose end is what settles the stance), so anything that replaced the clips
 * with a rotating single sprite would have had to reimplement that.
 *
 * The cost is 512 small textures built once at boot, which is cheaper than it
 * sounds beside the map bake's several thousand draws.
 *
 * ### The silhouette leads
 *
 * Every figure is drawn to fill its {@link Silhouette} box, so the shape on
 * screen and the shape that collides are the same shape by construction. The
 * boxes are the ones the old tracer measured, kept unchanged, so guard radii,
 * the player's body and every shadow are numerically identical to before.
 */

/** How a figure is posed for one frame of one animation. */
interface Pose {
  /** Position around the cycle, 0..1. Drives the walk stride and the idle bob. */
  phase: number;
  /** 0 standing, 1 fully crouched. Fractional during the lower/rise clips. */
  crouch: number;
  /** Stride reach, as a fraction of the silhouette's length. 0 when still. */
  stride: number;
}

/** A role's shapes and colours. */
interface CastRole {
  silhouette: Silhouette;
  /** Main body fill. */
  body: number;
  /** The head, and the shoulder line — a shade off the body so the two separate. */
  head: number;
  /** Highlight — visor, lens, insignia. Reads as the thing's "front". */
  accent: number;
  /** Outline and underside. */
  dark: number;
  /** Drones have a chassis and rotors where everyone else has a head and legs. */
  chassis?: boolean;
}

/**
 * Palettes picked to sit on the map's grey-blue concrete without blending into
 * it, and to say what each figure is before you have read anything: Rowan cool
 * and low-contrast, an enforcer hot, a drone the same cyan the engine uses for
 * every machine you can interact with, an orderly pale and soft.
 */
const ROLES: Record<string, CastRole> = {
  player: {
    silhouette: PLAYER_SILHOUETTE,
    body: 0x2f4f6f,
    head: 0x3d5a78,
    accent: 0xffe6a3,
    dark: 0x16212e,
  },
  enforcer: {
    silhouette: ENFORCER_SILHOUETTE,
    body: 0x6b2230,
    head: 0xb5535f,
    accent: 0xff8a3b,
    dark: 0x2a0f16,
  },
  drone: {
    silhouette: DRONE_SILHOUETTE,
    body: 0x2b4356,
    head: 0x4a6b85,
    accent: 0x39d3ff,
    dark: 0x16212e,
    chassis: true,
  },
  orderly: {
    silhouette: ORDERLY_SILHOUETTE,
    body: 0xd8dee6,
    head: 0xf0f3f7,
    accent: 0x41586f,
    dark: 0x6b7887,
  },
  /**
   * The human security guard. Deliberately reads closer to the orderly than to
   * the enforcer — same pale head, a uniform blue-grey body — because the one
   * thing his art has to say before anything else is *this one is a person*. The
   * red visor accent is the only hot colour on him, and it is the insignia rather
   * than a machine's lens: authority worn by someone, not built into them.
   */
  security: {
    silhouette: SECURITY_SILHOUETTE,
    body: 0x3f4a63,
    head: 0xe8d9c5,
    accent: 0xb5535f,
    dark: 0x1c2233,
  },
};

/** Points of a rotated ellipse, for `fillPoints` — Phaser only fills axis-aligned ones. */
function ellipsePoints(
  cx: number,
  cy: number,
  along: number,
  across: number,
  angle: number,
  segments = 18,
): Phaser.Types.Math.Vector2Like[] {
  const cos = Math.cos(angle);
  const sin = Math.sin(angle);
  const pts: Phaser.Types.Math.Vector2Like[] = [];
  for (let i = 0; i < segments; i++) {
    const t = (i / segments) * Math.PI * 2;
    const u = Math.cos(t) * along;
    const v = Math.sin(t) * across;
    pts.push({ x: cx + u * cos - v * sin, y: cy + u * sin + v * cos });
  }
  return pts;
}

/**
 * Draws one figure, filling its silhouette box, facing `angle`.
 *
 * ### Why the body doesn't rotate
 *
 * The silhouette boxes describe a **three-quarter** view, not a true overhead
 * one: the player's is 13 wide by 25 tall, which is a figure seen from above and
 * in front, head up-screen. So the body is drawn upright at every facing and only
 * the *head* turns — which is how the sheets this replaces worked, and it is not
 * merely a style choice. The player's Arcade body is one fixed 13×25 AABB whatever
 * way he faces; spin a 25-long figure to face east and the drawing is 25 wide
 * while the body it collides with is still 13, and the two part company.
 *
 * Back to front: legs, torso, shoulders, head, visor. The visor is the whole
 * facing cue, so it is the accent colour and it sits proud of the skull; turn to
 * face away and it disappears behind the head, which reads correctly as "looking
 * up-screen" rather than as a missing feature.
 */
function drawFigure(g: Phaser.GameObjects.Graphics, role: CastRole, angle: number, pose: Pose): void {
  const { aabb } = role.silhouette;
  const cx = aabb.offsetX + aabb.width / 2;
  const cy = aabb.offsetY + aabb.height / 2;
  // Half-extents of the box: `len` head-to-toe, `wid` across the shoulders.
  const len = aabb.height / 2;
  const wid = aabb.width / 2;

  if (role.chassis) {
    drawChassis(g, role, { cx, cy, len, wid }, angle, pose);
    return;
  }

  // Crouching folds the figure down and spreads it a little — the trade a person
  // makes going low. Everything below scales off these two.
  const squat = 1 - 0.34 * pose.crouch;
  const spread = 1 + 0.18 * pose.crouch;
  const swing = Math.sin(pose.phase * Math.PI * 2);
  // Idle breathes; walking swings. One phase value drives both.
  const bob = pose.stride === 0 ? swing * len * 0.03 : 0;
  const y = (down: number): number => cy + down * len * squat + bob;

  // Legs — two below the body, striding in opposition.
  g.fillStyle(role.dark, 1);
  for (const side of [-1, 1]) {
    const reach = len * pose.stride * swing * side;
    g.fillPoints(
      ellipsePoints(cx + side * wid * 0.42 * spread, y(0.6) + reach, wid * 0.3, len * 0.28 * squat, 0),
      true,
    );
  }

  // Torso — the bulk of the box, so the drawing and the collider agree.
  g.fillStyle(role.body, 1);
  g.fillPoints(ellipsePoints(cx, y(0.1), wid * 0.92 * spread, len * 0.48 * squat, 0), true);

  // Shoulders — a lighter band that separates the torso from the head and gives
  // the silhouette a waist at this size.
  g.fillStyle(role.head, 1);
  g.fillPoints(ellipsePoints(cx, y(-0.26), wid * 0.86 * spread, len * 0.16, 0), true);

  // Head, leaning the way it looks, with the face on its leading edge.
  //
  // A wedge was the obvious way to show facing and it does not survive the scale:
  // Rowan's head is 4px across at source, so any cone either vanishes or — sized
  // to be visible — reads as a searchlight rather than a face. Leaning the whole
  // head and marking its front is a bigger, coarser cue that still resolves when
  // the character is 36px tall on screen.
  const fx = Math.cos(angle);
  const fy = Math.sin(angle);
  const headR = wid * 0.66;
  const headX = cx + fx * headR * 0.34;
  const headY = y(-0.6) + fy * headR * 0.34;

  g.fillStyle(role.dark, 1);
  g.fillCircle(headX, headY, headR * 1.06);
  g.fillStyle(role.head, 1);
  g.fillCircle(headX, headY, headR * 0.86);
  g.fillStyle(role.accent, 1);
  g.fillCircle(headX + fx * headR * 0.44, headY + fy * headR * 0.44, headR * 0.42);
}

/**
 * The drone: a chassis on rotors, with no head to turn — the lens is the front.
 *
 * This one *does* rotate, and can: its box is 41×35, near enough square that
 * turning it keeps the drawing inside the silhouette. It is also a machine seen
 * from directly above rather than a figure seen at an angle, so rotating is what
 * it should look like.
 */
function drawChassis(
  g: Phaser.GameObjects.Graphics,
  role: CastRole,
  geom: { cx: number; cy: number; len: number; wid: number },
  angle: number,
  pose: Pose,
): void {
  const { cx, cy, len, wid } = geom;
  const fx = Math.cos(angle);
  const fy = Math.sin(angle);
  const rx = -fy;
  const ry = fx;
  const at = (fwd: number, side: number): { x: number; y: number } => ({
    x: cx + fx * fwd + rx * side,
    y: cy + fy * fwd + ry * side,
  });

  // Rotors first, so the chassis sits over their hubs. They counter-rotate with
  // the phase, which is the whole animation — a hovering thing has no gait.
  const spin = pose.phase * Math.PI * 2;
  g.fillStyle(role.dark, 1);
  for (const fwd of [-1, 1]) {
    for (const side of [-1, 1]) {
      const p = at(fwd * len * 0.62, side * wid * 0.66);
      g.fillCircle(p.x, p.y, wid * 0.3);
      g.lineStyle(2, role.accent, 0.55);
      g.beginPath();
      g.moveTo(p.x + Math.cos(spin) * wid * 0.28, p.y + Math.sin(spin) * wid * 0.28);
      g.lineTo(p.x - Math.cos(spin) * wid * 0.28, p.y - Math.sin(spin) * wid * 0.28);
      g.strokePath();
    }
  }

  g.fillStyle(role.body, 1);
  g.fillPoints(ellipsePoints(cx, cy, len * 0.66, wid * 0.5, angle), true);

  const lens = at(len * 0.42, 0);
  g.fillStyle(role.accent, 1);
  g.fillCircle(lens.x, lens.y, wid * 0.17);
}

/** Renders one pose into a texture, unless something already claimed the key. */
function bake(
  scene: Phaser.Scene,
  g: Phaser.GameObjects.Graphics,
  key: string,
  role: CastRole,
  dir: Dir8,
  pose: Pose,
): void {
  if (scene.textures.exists(key)) return;
  g.clear();
  drawFigure(g, role, angleOf(dir), pose);
  g.generateTexture(key, role.silhouette.frameWidth, role.silhouette.frameHeight);
}

/** Pose for frame `i` of `count`, given how the animation moves. */
function poseFor(i: number, count: number, crouch: number, stride: number): Pose {
  return { phase: count > 1 ? i / count : 0, crouch, stride };
}

/** How each of the player's clips is posed. `crouch` is a ramp on the transitions. */
function playerPose(anim: PlayerAnimName, i: number, count: number): Pose {
  const ramp = count > 1 ? i / (count - 1) : 1;
  switch (anim) {
    case "walk":
      return poseFor(i, count, 0, 0.1);
    case "run":
      return poseFor(i, count, 0, 0.17);
    case "crouch":
      return poseFor(i, count, 1, 0);
    case "crouch-walk":
      return poseFor(i, count, 1, 0.08);
    case "crouch-down":
      return { phase: 0, crouch: ramp, stride: 0 };
    case "crouch-up":
      return { phase: 0, crouch: 1 - ramp, stride: 0 };
    default:
      return poseFor(i, count, 0, 0);
  }
}

/**
 * Builds every character texture the game will ask for.
 *
 * Call once, from `BootScene.create`, before any scene that spawns a character.
 * Idempotent: a key that already exists is left alone, so a scene restart costs
 * nothing.
 */
export function buildCastTextures(scene: Phaser.Scene): void {
  const g = scene.make.graphics({ x: 0, y: 0 }, false);

  for (const anim of Object.keys(PLAYER_ANIM_FRAME_COUNTS) as PlayerAnimName[]) {
    const count = PLAYER_ANIM_FRAME_COUNTS[anim];
    for (const dir of DIRS_8) {
      for (let i = 0; i < count; i++) {
        bake(scene, g, playerFrameKey(anim, dir, i), ROLES.player, dir, playerPose(anim, i, count));
      }
    }
  }

  for (const anim of Object.keys(ORDERLY_ANIM_FRAME_COUNTS) as OrderlyAnimName[]) {
    const count = ORDERLY_ANIM_FRAME_COUNTS[anim];
    for (const dir of DIRS_8) {
      for (let i = 0; i < count; i++) {
        const pose = poseFor(i, count, 0, anim === "walk" ? 0.09 : 0);
        bake(scene, g, orderlyFrameKey(anim, dir, i), ROLES.orderly, dir, pose);
      }
    }
  }

  // Guards have one clip each — a patrol scan — so the phase is the only input.
  for (const [role, skin] of [
    [ROLES.enforcer, ENFORCER_SKIN],
    [ROLES.drone, DRONE_SKIN],
    [ROLES.security, SECURITY_SKIN],
  ] as [CastRole, GuardSkin][]) {
    for (const dir of DIRS_8) {
      for (let i = 0; i < skin.frameCount; i++) {
        bake(scene, g, skin.frameKey(dir, i), role, dir, poseFor(i, skin.frameCount, 0, 0.08));
      }
    }
  }

  g.destroy();
}
