/**
 * Article Zero collider generator — CLI runner.
 *
 * Traces a sprite PNG's alpha silhouette, simplifies it with Ramer–Douglas–
 * Peucker, and writes a generated TypeScript module holding a tight-fit AABB
 * (for Phaser Arcade `body.setSize`/`setOffset`) plus the simplified polygon
 * (for future Matter.js / line-of-sight use).
 *
 *   npm run gen:colliders                       # regenerate the player collider
 *   npm run gen:colliders -- --verbose          # + ASCII silhouette preview
 *   npm run gen:colliders -- --input assets/x.png --out src/entities/generated/x.ts \
 *                            --export FOO_COLLIDER --epsilon 2 --inset 0 --origin top-left
 *
 * Deterministic: same input + flags → byte-identical output.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { decodeRgba8 } from "./png";
import { alphaMask, largestComponent, traceContour } from "./contour";
import { rdp } from "./rdp";
import type { Point } from "./rdp";
import { toAABB, toPointObjects, toFlatArray, toMatterVertices } from "./format";
import type { AABB, Origin } from "./format";

interface Args {
  input: string;
  out: string;
  exportName: string;
  epsilon: number;
  inset: number;
  origin: Origin;
  threshold: number;
  verbose: boolean;
}

const DEFAULTS: Args = {
  input: "public/assets/player/idle/south/0.png",
  out: "src/entities/generated/playerCollider.ts",
  exportName: "PLAYER_IDLE_SOUTH_COLLIDER",
  epsilon: 2.0,
  inset: 0,
  origin: "top-left",
  threshold: 10,
  verbose: false,
};

function parseArgs(argv: string[]): Args {
  const args: Args = { ...DEFAULTS };
  for (let i = 0; i < argv.length; i++) {
    const flag = argv[i];
    const next = (): string => {
      const v = argv[++i];
      if (v === undefined) throw new Error(`missing value for ${flag}`);
      return v;
    };
    switch (flag) {
      case "--input":
        args.input = next();
        break;
      case "--out":
        args.out = next();
        break;
      case "--export":
        args.exportName = next();
        break;
      case "--epsilon":
        args.epsilon = Number(next());
        break;
      case "--inset":
        args.inset = Number(next());
        break;
      case "--origin": {
        const v = next();
        if (v !== "top-left" && v !== "center") {
          throw new Error(`--origin must be "top-left" or "center", got "${v}"`);
        }
        args.origin = v;
        break;
      }
      case "--threshold":
        args.threshold = Number(next());
        break;
      case "--verbose":
        args.verbose = true;
        break;
      default:
        throw new Error(`unknown argument: ${flag}`);
    }
  }
  return args;
}

/** Renders the mask with the simplified polygon vertices marked, for eyeballing. */
function asciiPreview(
  mask: { width: number; height: number; data: Uint8Array },
  polygon: Point[],
): string {
  const vertices = new Set(polygon.map((p) => `${Math.round(p.x)},${Math.round(p.y)}`));
  const lines: string[] = [];
  for (let y = 0; y < mask.height; y++) {
    let line = "";
    for (let x = 0; x < mask.width; x++) {
      if (vertices.has(`${x},${y}`)) line += "#";
      else line += mask.data[y * mask.width + x] === 1 ? "." : " ";
    }
    lines.push(line.replace(/\s+$/, ""));
  }
  return lines.join("\n");
}

function renderModule(args: Args, frameW: number, frameH: number, aabb: AABB, polygon: Point[]): string {
  const points = toPointObjects(polygon, args.origin, { width: frameW, height: frameH });
  const flat = toFlatArray(points);
  const matter = toMatterVertices(points);
  const polyLiteral = points.map((p) => `    { x: ${p.x}, y: ${p.y} }`).join(",\n");

  return `// AUTO-GENERATED by \`npm run gen:colliders\`. Do not edit by hand.
// Source: ${args.input} (${frameW}×${frameH}px)
// epsilon=${args.epsilon}, inset=${args.inset}, origin=${args.origin}, alphaThreshold=${args.threshold}

/** A sprite collider derived from its alpha silhouette. */
export interface SpriteCollider {
  /** Source sprite the collider was traced from. */
  readonly source: string;
  readonly frameWidth: number;
  readonly frameHeight: number;
  /** RDP tolerance (px) and edge inset (px) used to generate this data. */
  readonly epsilon: number;
  readonly inset: number;
  /**
   * Tight-fit box in the sprite's *unscaled* local space. Feed \`width\`/\`height\`
   * to Phaser Arcade \`body.setSize\` and \`offsetX\`/\`offsetY\` to \`body.setOffset\`.
   */
  readonly aabb: {
    readonly width: number;
    readonly height: number;
    readonly offsetX: number;
    readonly offsetY: number;
  };
  /** Simplified alpha contour (\`origin=${args.origin}\`), for polygon/LOS/Matter use. */
  readonly polygon: ReadonlyArray<{ readonly x: number; readonly y: number }>;
  /** \`polygon\` flattened to \`[x1, y1, x2, y2, ...]\`. */
  readonly polygonFlat: readonly number[];
  /** Path string for \`Matter.Vertices.fromPath\` / \`Bodies.fromVertices\`. */
  readonly matterPath: string;
}

export const ${args.exportName}: SpriteCollider = {
  source: ${JSON.stringify(args.input)},
  frameWidth: ${frameW},
  frameHeight: ${frameH},
  epsilon: ${args.epsilon},
  inset: ${args.inset},
  aabb: { width: ${aabb.width}, height: ${aabb.height}, offsetX: ${aabb.offsetX}, offsetY: ${aabb.offsetY} },
  polygon: [
${polyLiteral},
  ],
  polygonFlat: [${flat.join(", ")}],
  matterPath: ${JSON.stringify(matter)},
} as const;
`;
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  const buffer = readFileSync(args.input);
  const img = decodeRgba8(new Uint8Array(buffer.buffer, buffer.byteOffset, buffer.byteLength));

  const blob = largestComponent(alphaMask(img, args.threshold));
  const contour = traceContour(blob);
  const polygon = rdp(contour, args.epsilon);
  // The AABB drives the physics body, so take it from the raw silhouette
  // extent rather than the RDP polygon (which can shrink the box by ~epsilon).
  const aabb = toAABB(contour, args.inset);

  const module = renderModule(args, img.width, img.height, aabb, polygon);
  mkdirSync(dirname(args.out), { recursive: true });
  writeFileSync(args.out, module);

  const inFrame =
    aabb.width > 0 &&
    aabb.height > 0 &&
    aabb.offsetX >= 0 &&
    aabb.offsetY >= 0 &&
    aabb.offsetX + aabb.width <= img.width &&
    aabb.offsetY + aabb.height <= img.height;

  console.log(`collider: ${args.input} (${img.width}×${img.height})`);
  console.log(`  contour ${contour.length} px → polygon ${polygon.length} vertices (epsilon=${args.epsilon})`);
  console.log(`  aabb ${aabb.width}×${aabb.height} @ offset (${aabb.offsetX}, ${aabb.offsetY})${inFrame ? "" : "  ⚠ OUT OF FRAME"}`);
  console.log(`  wrote ${args.out}`);
  if (args.verbose) {
    console.log("\n" + asciiPreview(blob, polygon) + "\n");
  }
}

main();
